name: "Generate Engine Patch"
description: "Generates a patch file for an engine change"
author: "Charlie Cline"
inputs:
  parent_branch:
    description: 'Branch to use to generate patch'
    required: true
    default: 'main'
outputs:
  out_patch_file:
    description: "Patch file that was generated"
runs:
  using: "docker"
  image: "Dockerfile"
