name: "Generate Engine Patch"
description: "Generates a patch file for an engine change"
author: "Charlie Cline"
inputs:
  parent_branch:
    description: 'Branch to use to generate patch'
    required: true
    default: 'main'
  patches_dir:
    description: 'Folder to output patches'
    required: true
    default: 'patches'
  specific_folder:
    description: 'Top level folder to generate patches for'
    required: false
    default: '.'
outputs:
  out_patch_file:
    description: "Patch file that was generated"
runs:
  using: "docker"
  image: "Dockerfile"
